# Generated by Django 5.1.7 on 2025-03-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="certificate",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="private_key",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
